import type { Metadata } from "next";
import '@/styles/globals.css';
import '@/styles/main.css';
import { WithFullWidthFlyoutMenu } from "@/components/common/with-full-width-flyout-menu";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="">
      <body className="flex h-full w-dvw flex-col">
        <WithFullWidthFlyoutMenu />
        {children}
      </body>
    </html>
  );
}
